name: untitled67
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.5.4"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.5.0
  flutter_mobx: ^2.0.6
  provider: ^6.0.5

  # Flutter icons for iOS-like appearance
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true

  # Add asset management if needed
  # assets:
  #   - images/sample_image.png

  # Add custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
